# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  none

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '9b1f8363-6b3a-4ee6-9ab9-50b043ec189d'
  imageRepository: 'alokeghoshdotnetdockerfile'
  containerRegistry: 'globalacrdc.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-ag'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: alokeagent
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: CmdLine@2
      inputs:
        script: 'docker rmi -f globalacrdc.azurecr.io/alokeghoshdotnetdockerfile:$(Build.BuildId)'
    - task: Bash@3
      displayName: update the  manifest file for container image
      inputs:
        filePath: 'scripts/updateaksManifests.sh'
        arguments: '$(tag)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/azure-vmss'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1 
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy_in_vmss
  displayName: "Release Stage"
  pool:
    name: alokeagent
    vmImage: $(vmImageName)
  jobs:
  - deployment: deploy_job
    environment: 'vmss-test'
    strategy:
        runOnce:
           deploy:
             steps:
             - task: replacetokens@6
               displayName: 'replace token'
               inputs:
                root: '$(Pipeline.Workspace)/drop'
                sources: 'cloud-init.txt'

